config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :my_threads do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_thread
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  # authentication_keys: %i[email username]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    def configure_permitted_parameters
        added_attrs = [ :name, :email, :password ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    end
    def after_sign_up_path_for(resource)
        my_threads_path
    end

    def after_sign_in_path_for(resource)
        my_threads_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
  end

  def new
    # @my_thread = MyThread.find(params[:my_thread_id])
    @comment = Comment.new
  end

  def create
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = @my_thread.comments.new(comment_params)
    if @comment.save
      redirect_to my_thread_path(@my_thread)
    else
      render :new
    end
  end

  def edit
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = @my_thread.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to my_thread_path(@comment.my_thread)
    else
      render :edit
    end
  end

  def destroy
    @my_thread = MyThread.find(params[:my_thread_id])
    @comment = @my_thread.comments.find(params[:id])
    @comment.destroy
    redirect_to my_thread_path
  end


  private
  def comment_params
    params.require(:comment).permit(:text)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  def index
    @my_threads = MyThread.all
  end

  def show
    @my_thread = MyThread.find(params[:id])
  end

  def new
    @my_thread = MyThread.new
  end

  def create
    @my_thread = MyThread.new(thread_params)
    if @my_thread.save
      redirect_to my_threads_path
    else
      render :new
    end
  end

  def destroy
    @my_thread = MyThread.find(params[:id])
    @my_thread.destroy
    redirect_to my_threads_path
  end

  def edit
    @my_thread = MyThread.find(params[:id])
  end

  def update
    @my_thread = MyThread.find(params[:id])
    if @my_thread.update(thread_params)
      redirect_to my_threads_path
    else
      render :edit
    end
  end

  private
    def thread_params
      params.require(:my_thread).permit(:text)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    my_threads_path

  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_threads/comments_helper.rb
module MyThreads::CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [:my_thread,comment]) do |form| %>
  <div>
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing my thread</h1>

<%= render 'form' , comment: @comment %>

<div>
  <%= link_to "Show this my thread", @my_thread %> 
  <%= link_to "Back to my threads", my_threads_path %>
</div>

app/views/comments/new.html.erb
<h1>New my thread</h1>

<%= render 'form' ,comment: @comment %>
<br>

<div>
  <%= link_to "Back to my threads" , my_threads_path %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardPlus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread) do |form| %>
  <div>
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/my_threads/edit.html.erb
<h1>Editing my thread</h1>

<%= render 'form' , my_thread: @my_thread %>

<div>
  <%= link_to "Show this my thread", @my_thread %> 
  <%= link_to "Back to my threads", my_threads_path %>
</div>

app/views/my_threads/index.html.erb
<h1>My Thread</h1>
<h2>ようこそ</h2>
<%= link_to "create new thread", new_my_thread_path%>
<br>
<br>
<% @my_threads.each do | my_thread |%>
  <div>
    <%=  link_to my_thread.text ,my_thread %>
  </div>
  <br>
<% end %>

app/views/my_threads/new.html.erb
<h1>New my thread</h1>

<%= render 'form' ,my_thread: @my_thread %>
<br>

<div>
  <%= link_to "Back to my threads" , my_threads_path %>
</div>

app/views/my_threads/show.html.erb
<h1>My Thread </h1>
<%= @my_thread.text %>
<%= link_to "Back to my thread", my_threads_path %>
<%= button_to "消去" , my_thread_path(@my_thread), method: :delete , form: {data: { turbo_confirm: 'Sure?' }} %>
<%= button_to "編集" , edit_my_thread_path(@my_thread), method: :get %>
<br>

<%= link_to "Create new comment", new_my_thread_comment_path(@my_thread)%>

<div>
  <h3>comment</h3>
  <ul>
    <% @my_thread.comments.each do |comment|%>
      <li><%= comment.text %></li>
      <%= button_to "消去" , my_thread_comment_path(@my_thread,comment), method: :delete , form: {data: { turbo_confirm: 'Sure?' }} %>
      <%= button_to "編集" , edit_my_thread_comment_path(@my_thread,comment), method: :get %>
    <% end %>
  </ul>
</div>